# Site settings
title: Sabrina Peters
email: brideeray@gmail.com
description: "I'm a library assistant, researcher, and MLIS student."
baseurl: ""
url: "http://sabrinapeters.net"

exclude: ["node_modules", "package.json", "Gruntfile.js"]

# Build settings
markdown: kramdown
permalink: pretty
