# Site settings
title: Sabrina Reyes-Peters
email: brideeray@gmail.com
description: "a blog about faith & dismantling the kyriarchy"
subtitle: "stomping the kyriarchy with ordinary words"
baseurl: ""
url: "http://www.sdrp.me"

exclude: ["node_modules", "paths.js", "package-lock.json", "package.json", "gulpfile.babel.js"]

# Build settings
markdown: kramdown
permalink: pretty
