# Site settings
title: Sabrina Peters
email: brideeray@gmail.com
description: "I'm a library assistant, researcher, and MLIS student at the University of Washington (incoming Fall 2014)."
baseurl: ""
url: "http://sabrinapeters.net/"

# Build settings
markdown: kramdown
permalink: pretty
