# Site settings
title: Sabrina Peters
email: brideeray@gmail.com
description: "I'm a MLIS student, librarian-in-training, and aspiring agitator for good."
baseurl: ""
url: "http://sabrinapeters.net"

exclude: ["node_modules", "package.json", "Gruntfile.js"]

# Build settings
markdown: kramdown
permalink: pretty
