# Site settings
title: Sabrina Reyes-Peters
email: brideeray@gmail.com
description: "disturber of the kyriarchy • staunch bibliophile • wandering mdiv"
subtitle: ""
baseurl: ""
url: "http://www.sdrp.me"

exclude: ["node_modules", "package.json", "Gruntfile.js"]

# Build settings
markdown: kramdown
permalink: pretty
