name: Scheduled builds
on:
  schedule:
    - cron: '0 9 * * *'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel
        run: curl -X GET ${{ secrets.vercel_webhook }}
      
