on: [push, pull_request]

name: Node CI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

    steps:
      - uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps and build package
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
        env:
          CI: TRUE
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOG_INDEX_ID: ${{ secrets.BLOG_INDEX_ID }}
